default_configure_args:
    - version-git

targets:
    dist-avr:
        task_script: build-aux/ci.sh
        archive_filter: "dwtk-ice-*.tar.gz"
    dist-avr-debug:
        task_script: build-aux/ci.sh
        archive_filter: "dwtk-ice-*-debug.tar.gz"
