name: yatr
on:
  push:
    paths-ignore:
      - '.github/workflows/kicad.yaml'
      - 'hardware/**'
      - 'images/**'

jobs:
  yatr:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        target:
          - dist-attiny4313
          - dist-attiny4313-debug
          - dist-atmega88pa
          - dist-atmega88pa-debug
          - dist-atmega8u2
          - dist-atmega8u2-debug
          - dist-atmega32u2
          - dist-atmega32u2-debug

    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Run yatr
        env:
          TARGET: "${{ matrix.target }}"
          DISTFILES_URL: "${{ secrets.DISTFILES_URL }}"
        run: curl -sSf https://yatr.rgm.io/run.sh | bash
